version: "3.7"

services:
    virtuoso:
        image: tenforce/virtuoso
        environment:
            VIRT_Parameters_DirsAllowed: ., /usr/local/virtuoso-opensource/share/virtuoso/vad, /virtuoso/data
        volumes:
            - files:/virtuoso/data
        ports:
            - "8890:8890"

    importer:
        build: ./
        command: /virtuoso/envsetter.sh # Use whatever script you need here
        environment:
            DBA_PASSWORD: ${DBA_PASSWORD}
            VIRTUOSO_DATA_DIR: /virtuoso/data
            GIT_REPO: ${GIT_REPO}
            GRAPH_URI: ${GRAPH_URI}
            GIT_EMAIL: ${GIT_EMAIL}
            GIT_NAME: ${GIT_NAME}
            CRON_JOB: ${CRON_JOB} #update or import
        volumes:
            - files:/virtuoso/data
            - ./id_rsa:/root/.ssh/id_rsa
            - ./config:/root/.ssh/config

volumes:
    files: {}
